# Generated by Django 5.1.3 on 2024-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=10,
                    ),
                ),
                ("server_response", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытка рассылок",
                "permissions": [
                    ("can_view_all_mailings_attempts", "can view all mailings attempts")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMailingStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_mailings", models.PositiveIntegerField(default=0)),
                ("successful_mailings", models.PositiveIntegerField(default=0)),
                ("failed_mailings", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "can view all mailings"),
                    ("can_disable_mailings", "can disable mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_all_messages", "can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_all_recipients", "can view all recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
